name: Python application test  with GitHub Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: | 
        make install

    - name: Lint with Pyling
      run: |
        make lint

    - name: Test with Pytest
      run: |
        make test

    - name: Format code with Python black
      run: |
        make format
